# Generated by Django 4.1 on 2022-11-21 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentSancfis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('longitude', models.FloatField(max_length=20, null=True)),
                ('latitude', models.FloatField(max_length=20, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('agent_sancfis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.agentsancfis')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleConsultation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('dateEmbauche', models.DateField()),
                ('dateResiliation', models.DateField()),
                ('statut', models.BooleanField()),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleExamen', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Forme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Frequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Masse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masse', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleMedicament', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='policeAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('taux', models.IntegerField()),
                ('datePriseEffet', models.DateField()),
                ('dateFin', models.DateField()),
                ('statutModification', models.BooleanField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('agent_assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.agentassurance')),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellePrestation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Quantite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=40)),
                ('ville', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='voieAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Souscripteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('longitude', models.FloatField(max_length=40, null=True)),
                ('latitude', models.FloatField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('agent_assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.agentassurance')),
                ('assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.assurance')),
                ('police_assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.policeassurance')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('longitude', models.FloatField(max_length=40, null=True)),
                ('latitude', models.FloatField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('agent_sancfis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.agentsancfis')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOrdonnance', models.CharField(max_length=40)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.examen')),
                ('forme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.forme')),
                ('frequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.frequence')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.medicament')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.moment')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.nombre')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.periode')),
                ('quantite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.quantite')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.unite')),
                ('voie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.voieadministration')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('longitude', models.FloatField(max_length=40, null=True)),
                ('latitude', models.FloatField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('agent_sancfis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.agentsancfis')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville')),
            ],
        ),
        migrations.CreateModel(
            name='centreDeSoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('longitude', models.FloatField(max_length=40, null=True)),
                ('latitude', models.FloatField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('agent_sancfis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.agentsancfis')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('numero', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('dateNaiss', models.DateField()),
                ('lieuNaiss', models.CharField(max_length=40, null=True)),
                ('taille', models.FloatField(max_length=4, null=True)),
                ('masse', models.FloatField(max_length=6, null=True)),
                ('defautSante', models.CharField(max_length=40, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('ayantDroit', models.BooleanField()),
                ('statut', models.BooleanField()),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('agent_assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.agentassurance')),
                ('police_assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.policeassurance')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville')),
            ],
        ),
        migrations.AddField(
            model_name='assurance',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville'),
        ),
        migrations.AddField(
            model_name='agentsancfis',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville'),
        ),
        migrations.CreateModel(
            name='AgentPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.pharmacie')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.laboratoire')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.centredesoins')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville')),
            ],
        ),
        migrations.AddField(
            model_name='agentassurance',
            name='assurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.assurance'),
        ),
        migrations.AddField(
            model_name='agentassurance',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentassurance',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.ville'),
        ),
        migrations.CreateModel(
            name='AdminSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, null=True)),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
                ('pays', models.CharField(max_length=40, null=True)),
                ('profession', models.CharField(max_length=40, null=True)),
                ('genre', models.CharField(choices=[('MASCULIN', 'masculin'), ('FEMININ', 'feminin')], max_length=10, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
