# Generated by Django 4.1.3 on 2023-01-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taux_pa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='policeassurance',
            name='taux',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.taux_pa'),
        ),
    ]
