# Generated by Django 4.1.3 on 2022-11-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0002_agentsancfis_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsancfis',
            name='admin',
        ),
    ]
