# Generated by Django 4.1.3 on 2022-11-28 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0003_remove_agentsancfis_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsancfis',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.adminsysteme'),
        ),
    ]
